root: true
extends:
  - neon/common
  - neon/node
  - neon/typescript
  - neon/prettier
  - neon/module
parserOptions:
  project: ./tsconfig.json
ignorePatterns:
  - '**/dist/*'

reportUnusedDisableDirectives: true
rules:
  '@typescript-eslint/lines-between-class-members': off
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/prefer-literal-enum-member': off
  promise/prefer-await-to-callbacks: off
  typescript-sort-keys/interface: off
  unicorn/no-static-only-class: off
  unicorn/prefer-math-trunc: off
  id-length: off
