root: true
parser: '@typescript-eslint/parser'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:unicorn/recommended
  - prettier
plugins:
  - '@typescript-eslint'
  - import
  - simple-import-sort

reportUnusedDisableDirectives: true
rules:
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/explicit-function-return-type': error
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-non-null-assertion': 'off'
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
  simple-import-sort/exports: error
  simple-import-sort/imports: error
  unicorn/filename-case: 'off'
  unicorn/no-null: 'off'
  unicorn/no-static-only-class: 'off'
  unicorn/prefer-math-trunc: 'off'
  unicorn/prevent-abbreviations: 'off'
  curly:
    - error
    - multi
